project:
  type: website
  output-dir: docs

website:
  title: "sherilyntsh.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: datastory.qmd
        text: Data Story
      - href: datavisual.qmd
        text: Data Visualization
      - href: conclusion.qmd
        text: Conclusion

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual
