---
title: "About"
---

Welcome to my website!

# Introduction

Welcome to Sherilyn's GitHub! Here is where all the progress of my work from NM2207 will be kept and also my final project. The data story that I have decided to work on is about dogs. I am going to create an app using shiny to help users to visualize which dog breed group is the most popular and why is that so.

# Data Set

The links to the data set can be found below:

akc data latest - <https://www.kaggle.com/datasets/mexwell/dog-breeds-dataset>

# Data Story
The data story that I will be telling is about the top 100 most popular dog breeds and their respective characteristics as to why they are the most popular.

# Data Selection & Visualization

I will be using the columns breeds, popularity, group, min_height, max_height, min_weight, max_weight, min_expectancy, max_expectancy, shedding_value, energy_level_value and trainability_value.

There will be 3 kinds of visualization. First is "Table". Iit is a table that shows users the whole data set of the top 100 dog breeds and also filter through the data set. Second is "Plot Summary". It is a bar chart visualization to see the relationship between the most popular dog groups and their respective characteristics. Third is "Plot Working Group". From the "Plot Summary" it can be seen that the 'Working Group' is the most popular breed group in the top 100 thus this density plot visualization will show the different characteristic distribution of the working group dogs.

# Shiny Application

```{=html}
https://sherilyntangnm2207.shinyapps.io/MyShinyApp/<iframe height="400" width="100%" frameborder="no" src="https://sherilyntangnm2207.shinyapps.io/MyShinyApp/" </iframe>
```
